definitions:
  httputil.HTTPError:
    properties:
      code:
        example: 400
        type: integer
      message:
        example: status bad request
        type: string
    type: object
  models.Transaction:
    properties:
      amount:
        type: number
      date:
        type: string
      description:
        type: string
      id:
        type: integer
    type: object
  models.TransactionWithExchange:
    properties:
      converted_value:
        type: number
      country:
        type: string
      currency:
        type: string
      date:
        type: string
      description:
        type: string
      effective_date:
        type: string
      exchange_rate:
        type: number
      id:
        type: integer
      original_value:
        type: number
    type: object
info:
  contact: {}
paths:
  /transactions:
    get:
      consumes:
      - application/json
      description: Rota para capturar todas as transações
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Transaction'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Capturar todas as transações
      tags:
      - transaction
    post:
      consumes:
      - application/json
      description: Rota para criar uma nova transação
      parameters:
      - description: Modelo de transação
        in: body
        name: transaction
        required: true
        schema:
          $ref: '#/definitions/models.Transaction'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Transaction'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Criar uma transação
      tags:
      - transaction
  /transactions/{id}:
    get:
      consumes:
      - application/json
      description: Rota para capturar uma nova transação
      parameters:
      - description: Id da transação
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Transaction'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Capturar uma transação
      tags:
      - transaction
  /transactions/{id}/{currency}:
    get:
      consumes:
      - application/json
      description: Rota para capturar uma transação com a taxa da câmbio
      parameters:
      - description: Id da transação
        in: path
        name: id
        required: true
        type: integer
      - description: Moeda
        in: path
        name: currency
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.TransactionWithExchange'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Capturar uma transação com a taxa da câmbio
      tags:
      - transaction
swagger: "2.0"
